### ISSUE TITLE
无 token 时授权登录失败

### ISSUE THREAD

**Issue by dongguoduodong** [Serverless-Devs/registry-cli#1]
环境：mac os
问题描述：
执行命令：s cli registry login 时，授权后跳转的页面显示授权登录失败
<img width="641" alt="image" src="https://user-images.githubusercontent.com/62697469/159123527-4059838a-5398-4bd5-888d-d8590ba75dff.png">
通过 直接复制 url 中显示的 token，通过 s cli registry login --token <token> 命令登录成功

**Comment by anycodes** [comment]
1. 授权失败大概率适合网络有关的；因为国内访问Github确实会有网络问题；可以稍后再试；
2. URL中的Token并不是登陆token，你复制出来强行配置进行也是没用的；

**Comment by dongguoduodong** [comment]
您好，我已收到您的邮件，会尽快给您回复。

**Comment by anycodes** [comment]
之前对这个问题是有了解的。因为服务端需要根据一些token等信息，进行GIthub的授权操作，但是Github的接口在国内又经常访问失败，所以你这次的提问，也督促了我快速的升级了后端的这个功能。

- 之前的：客户端->Github授权->回调到国内的服务器->国内服务器请求Github接口（这里经常性挂掉）->返回结果给客户端
- 现在的：客户端->Github授权->回调到国内的服务器->内部通道连接到海外服务器->国内服务器请求Github接口->返回结果给国内服务器->返回结果给客户端

目前通过海外服务器做一次转发，整个访问Github接口失败的问题，基本修复了。

- Q：如果国内服务器访问海外服务器失败怎么办？
- A：可能会失败，但是大概率不会，这个是有专线访问的，网络也经过优化。

刚才在国内的机器上测试了几次，Github的接口依旧不通：
![image](https://user-images.githubusercontent.com/21079031/159127543-1bbc4901-ff59-4829-a277-653ccb4aa152.png)

但是，升级了之后，在海外机器请求的，基本都已经可以授权成功了：
![image](https://user-images.githubusercontent.com/21079031/159127562-c62ed2e3-33d9-49fa-8b93-43560a08bc62.png)

测试了几次，没有失败。你这里可以重新发起登陆操作：`s cli registry login`

**Comment by dongguoduodong** [comment]
好的，谢谢鸭～
