### ISSUE TITLE
使用 0.0.6 版 registry 组件无法删除自己创建的包

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/registry-cli#2]
![lQLPDhtrZx-19knNAZPNBBCw-fxP4p-HDEMCgKRZjIDTAA_1040_403](https://user-images.githubusercontent.com/16363180/168224640-78cb2cb4-2c8e-421d-adf7-6aae96f6f56f.png)

**Comment by DevDengChao** [comment]
@anycodes 请问是修复了么?

**Comment by anycodes** [comment]
目前我看是修复了，你这里体验还有问题是么

**Comment by DevDengChao** [comment]
我看到 issue 下没有任何评论就被关闭了, 所以问一下是什么情况.

刚刚尝试着查询了一下自己已发布的包的版本, 发现 0.0.0 版已经不见了. 🤣

**Comment by DevDengChao** [comment]
后续我再尝试删除一下其他的版本看看.

**Comment by DevDengChao** [comment]
确实可以删除了.

![image](https://user-images.githubusercontent.com/16363180/168578460-2f623f8a-57a5-45bc-a4b8-002a29a72c04.png)
