### ISSUE TITLE
使用 0.0.8 版 registry 查看已发布的插件版本时只显示最新的一个版本信息

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/registry-cli#4]
![image](https://user-images.githubusercontent.com/16363180/168566931-8853e26e-9e7d-46b2-aaff-137a148939ee.png)
![image](https://user-images.githubusercontent.com/16363180/168566797-cfac5b28-ab51-4a39-8b2b-45c1793abbe7.png)

**Comment by anycodes** [comment]
用这个命令查看某个package的所有信息：https://github.com/serverless-devs/registry#%E6%9F%A5%E7%9C%8B%E6%9F%90-package-%E6%8C%87%E5%AE%9A%E7%89%88%E6%9C%AC%E4%BF%A1%E6%81%AFdetail
